apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
     app: nginx
  ports:
  - protocol: TCP
    port: 80        # service port
    targetPort: 80   # target port in the pod
    nodePort: {{ .Values.service.nodeport }} # custom NodePort